name: Build & Deploy to Github Pages
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and Deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: jackfiled/wiki
        TARGET_BRANCH: gh_pages
        BUILD_SCRIPT: git config --global --add safe.directory "*" && npm install && npm run docs:build
        BUILD_DIR: docs/.vuepress/dist/